title: <p align="center"> R.M. </p>

logo: "/assets/img/profile_img.jpg?raw=true"

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://github.com/rm178">GitHub</a>
  </p>
  
  <p align="justify">
  I am pursuing MS degree in Data science at the School of Science & Technology, IHU.
  <br><br>
  My first degree is in Physics
  <br><br>
  </p>
  
theme: jekyll-theme-minimal

